language: python
python:
  - "3.6"

# Make sure libsodium dependency is present
before_install:
  - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.16.tar.gz
  - tar -zxvf libsodium-1.0.16.tar.gz
  - cd libsodium-1.0.16
  - ./configure
  - make && make check
  - sudo make install
  - cd ..

install:
  # In the future we may need to change this to pull didery from github instead of Pypi
  - pip install didery
  - pip install -e ../didery.py
  - dideryd &
  - dideryd --port=8000 &

# Run Tests
script:
  - pytest tests/ -vv